### ISSUE TITLE
Some requests about backendRequests.js

### ISSUE THREAD

**Issue by moran991231** [3-2-sw-engineering/find_snack_cart#12]
# SignUp
1. isIdAvailable (id:string) -> boolean  
회원가입하려고 하는 아이디 중복확인하여 사용할 수 있는지 체크  

2. sendSignUpCode(email:string) -> (???)
이메일 인증을 위한 코드 발송.
이메일 추후 이메일 코드를 확인하기 위한 인자를 반환할 수도 있음.

3. checkSignUpCode(code:string) -> boolean
받은 이메일 코드를 확인함. 

4. createUser(..., isOwner)
사용자가 사장님 사용자인지 입력하는 입력 매개변수 추가 필요

# Manage (내 가게 관리하기)
1. createMarket, editMarket 입력 매개변수
location: 장소 (string) --> 'string의 배열'로 변경
food: 파는 음식들 (string의 배열) --> categories로 변경
category: 포장마차의 카테고리 (string) --> 삭제 
images: 이미지 경로 배열 (string의 배열) --> 미정...
authority: 0이면 일반 사용자, 1이면 사장님
fixed: 0이면 이동형, 1이면 고정형 -->삭제 

## comment 내용
* 이메일 인증코드: 아직은 이메일로 코드를 보내지는 못하므로 아무 문자열이나 넣어도 이메일 인증코드 승인이 되도록하자.
* market
> `market_category: String` 항목 삭제
> 'market_name:String' 항목 추가
> createMarket(...)은 생성된 market에 대한 index를 반환한다.
> 마켓을 만든 사장님 사용자의 `managing`필드에 생성한 market_index를 세팅하기 위한 api필요

**Comment by powergee** [comment]
* **sendSignUpCode(email:string)**
  이메일로 발송된 코드의 유효기간은 3분(180초)로 하겠습니다. 그리고 아직 백엔드에서 실제 메일을 보낼 수 없기 때문에 API는 구현하되 checkSignUpCode(code:string)에서 임의의 문자열을 넣어도 true를 반환하도록 일단 구현해놓고 메일을 보내는 방법을 알아보겠습니다.

* **food: 파는 음식들 (string의 배열) --> categories로 변경**
  반환되는 결과를 categories 라는 이름으로 바꾸라는 말씀이신가요?

**Comment by moran991231** [comment]
createMarket, editMarket 함수들의 매개변수 중 `food :[string]`과 `category :string` 이 있습니다.
두 항목 모두 음식 카테고리를 의미하므로 둘 중에 하나만 있어도 됩니다.
현재 한 포장마차 당 여러 개의 음식 카테고리를 선택할 수 있으므로 `category :string`항목을 삭제하고` food: [string]`항목을  카테고리로 사용하면 될 거 같습니다.
`category :string`만 삭제하면 될 거 같습니다!

**Comment by moran991231** [comment]
+) createMarket과 editMarket의 구분되어야 할 필요가 있나요?

**Comment by moran991231** [comment]
+) user의 managing (사장님 소유의 포장마차)는 BackendRequest.js의 `getmarketInfo(marketIdx)`함수에 사용할 수 있는 인덱스인가요?

**Comment by moran991231** [comment]
**지금보니 중요한 내용이 빠졌네요**
사장님 사용자의 경우 가게를 등록하면 user데이터에 managing 하는 포장마차를 등록할 수 있어야 합니다.
이부분은 어케 해야 하나요?!

**Comment by powergee** [comment]
> +) createMarket과 editMarket의 구분되어야 할 필요가 있나요?

그 둘은 목적과 동작이 다르고, 하나가 다른 하나를 대체할 수 없습니다.

createMarket은 이전에 존재하지 않던 포장마차를 새로 생성하는 것이므로, 이 API를 호출하면 새로운 포장마차 데이터를 초기화하면서 새 Index를 부여합니다.

editMarket은 이미 존재하는 포장마차를 Index로 조회하여 그 포장마차의 데이터를 수정합니다.

createMarket으로 새로운 Index가 생성되고, editMarket에서는 기존의 Index가 필요하므로 이를 구분없이 합치는 것은 현재 구조에서는 어렵습니다.

**Comment by powergee** [comment]
> +) user의 managing (사장님 소유의 포장마차)는 BackendRequest.js의 `getmarketInfo(marketIdx)`함수에 사용할 수 있는 인덱스인가요?

네, managing은 market의 index를 나타내므로 그 함수에서 이용할 수 있습니다.

**Comment by powergee** [comment]
> **지금보니 중요한 내용이 빠졌네요** 사장님 사용자의 경우 가게를 등록하면 user데이터에 managing 하는 포장마차를 등록할 수 있어야 합니다. 이부분은 어케 해야 하나요?!

처음 사장님 계정을 생성하고 나면 아직 관리하는 가게가 없으므로 managing이 null입니다. 이후 market을 새로 create 해서 가게를 등록해야 합니다.

... 그런데 API에서 market 생성할 때 관련 정보를 안받고 있군요... 시정하겠습니다 :cry:

**Comment by moran991231** [comment]
> > **지금보니 중요한 내용이 빠졌네요** 사장님 사용자의 경우 가게를 등록하면 user데이터에 managing 하는 포장마차를 등록할 수 있어야 합니다. 이부분은 어케 해야 하나요?!
> 
> 처음 사장님 계정을 생성하고 나면 아직 관리하는 가게가 없으므로 managing이 null입니다. 이후 market을 새로 create 해서 가게를 등록해야 합니다.
> 
> ... 그런데 API에서 market 생성할 때 소유자 관련 정보를 안받고 있군요... 시정하겠습니다 😢

market에서 소유 사용자의 정보를 보관하는 항목이 디비스키마에는 없습니다.

**Comment by moran991231** [comment]
+) market에 마켓 이름 항목도 추가해 주세욤
코멘트 내용 이슈에 정리하겠습니다.

**Comment by moran991231** [comment]
Good Job!
